name: 'Action to docker autoproj'
description: 'GitHub Action for run autoproj projects in docker container'
inputs:
  distro-name:
    description: 'Ubuntu distribution'
    required: true
  project-name:
    description: 'Ubuntu distribution'
    required: true
  bootstrap:
    description: >
      address package build conf containing all 
      commands to install download and install packages
    required: true
  user-name:
    description: 'Github user pusher email'
    required: true
  user-mail:
    description: 'Github user pusher name'
    required: true  
  ssh-key:  
    description: >
      SSH key used to fetch the repository. The SSH key is configured with the local
      git config, which enables your scripts to run authenticated git commands.
      The post-job step removes the SSH key.
    required: false  
runs:
  using: 'composite'
  steps:
    - id: docker-autoproj
      shell: bash
      run: ./runner.sh
      env:
        DISTRO:  ${{ inputs.distro-name }}
        PROJECT: ${{ inputs.project-name }}
        BOOTSTRAP_URL: ${{ inputs.bootstrap }}
        USER_NAME: ${{ inputs.user-name }}
        USER_EMAIL: ${{ inputs.user-mail }}
