name: 'Action to docker autoproj'
description: 'GitHub Action for run autoproj projects in docker container'
inputs:
  distro-name:
    description: "Ubuntu distribution"
    required: true
  project-name:
    description: "Ubuntu distribution"
    required: true
  docker-file:
    description: >
     'File that contains all the commands a user could call on the command line to assemble an image'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  build-args:
    DISTRO_NAME: ${{ inputs.distro-name }}
    PROJECT-NAME: ${{ inputs.project-name}}
  args:
    - ${{ inputs.distro-name }}
  env:
    DISTRO_NAME: ${{ inputs.distro-name }}
    PROJECT-NAME: ${{ inputs.project-name}}
